### PR TITLE
first test

### PR DESCRIPTION
**Pull request by AshleyQian**

### CODE REVIEW

**Comment by devietti** [comment]
Please immediately delete the repo at https://github.com/AshleyQian/cis5710-homework and restart with a private repo instead.

**Comment by AshleyQian** [comment]
Sorry, sir. Please give me some time, I don't know how to solve it.


| |
feb_weald0202
|
|
***@***.***
|
---- Replied Message ----
| From | Joseph ***@***.***> |
| Date | 2/3/2024 16:48 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
State ***@***.***> |
| Subject | Re: [cis5710/cis5710-homework] first test (PR #2) |

Please immediately delete the repo at https://github.com/AshleyQian/cis5710-homework and restart with a private repo instead.

**Comment by AshleyQian** [comment]
Sorry, sir. I have deleted the repo. Is this okay?


| |
feb_weald0202
|
|
***@***.***
|
---- Replied Message ----
| From | Joseph ***@***.***> |
| Date | 2/3/2024 16:48 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
State ***@***.***> |
| Subject | Re: [cis5710/cis5710-homework] first test (PR #2) |

Closed #2.

**Comment by devietti** [comment]
Unfortunately, the PR and its commits are still here. I guess it makes sense they want to archive them even if the repo/fork they came from disappeared. I'll contact GitHub support to get this deleted.

**Pull request closed without merging**
